[HTTP]
server                   = 0.0.0.0:8090
跨域                   = true
跨域白名单          = *
临时读写清理周期 = 60

[WebSocket]
启用       = false
访问路径 = ws
跨域       = true

[管理面板]
启用       = true
访问路径 = nebula/test

[词库调试]
# 词库调试页面的初始默认配置
默认词库 = private/debug.n
触发文本 = Main
保存运行 = true
实时保存 = true
超时       = 15
