[QQ]
启用 = false
词库 = private/bot/qq/dic.n
访问路径 = qq-bot
APPID = 123456
密钥 = xxx

[NapCat]
# 包含特殊符号需要放在双引号中
启用 = false
词库 = private/bot/napcat
访问路径 = napcat
发送消息接口 = http://127.0.0.1:3000
# 此处填HTTP服务器的Token不是HTTP客户端的，更换登录账号需要进机器人消息端webUI重新获取，每个账号对应一个
密钥 = "xxx"

[云湖]
启用 = false
词库 = private/bot/yunhu/dic.n
访问路径 = yunhu-bot
密钥 = xxx

[飞书]
启用 = false
词库 = private/bot/feishu
访问路径 = feishu-bot
APPID = cli_xxx
密钥 = xxx