[HTTP]
server = 0.0.0.0:8080
跨域 = true
跨域白名单 = "*"
临时读写清理周期 = 60

[WebSocket]
启用 = false
访问路径 = "ws"
跨域 = true

[管理面板]
启用 = true
访问路径 = nebula

[Ngrok]
启用 = false
密钥 = xxx
# 留空获取随机域名，仅限Ngrok域名
访问链接 = ""

[FRP]
启用 = false
# BeerWebFrp 服务端 WebSocket 地址（默认端口 8666）
服务端地址 = wss://frp.cjxpj.com
令牌 =
调试 = false

[FTP]
启用 = false
端口 = 21
用户名 = admin
密码 = 
调试 = false
TLS = true
PASV端口起始 = 32000
PASV端口结束 = 32005

[SFTP]
启用 = false
端口 = 22
用户名 = root
密码 = 
调试 = false